apiVersion: v1
kind: ConfigMap
metadata:
  name: department-service-config
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
  zap-logger-config.json: |
{{ .Files.Get "files/zap-logger-config.json" | indent 4 }}

  gorm-logger-config.json: |
{{ .Files.Get "files/gorm-logger-config.json" | indent 4 }}
