{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /v1/departments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: department-service
                port:
                  number: {{ .Values.ingress.department.servicePort }}
          - path: /v1/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.ingress.user.servicePort }}
{{- end }}
