apiVersion: v1
kind: ConfigMap
metadata:
  name: point-service-config
data:
  DATABASE_URL: {{  .Values.secret.DATABASE_URL | quote }}
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
  zap-logger-config.json: |
{{ .Files.Get "files/zap-logger-config.json" | indent 4 }}

  gorm-logger-config.json: |
{{ .Files.Get "files/gorm-logger-config.json" | indent 4 }}